(define (domain sokoban)
  (:requirements :strips :typing :negative-preconditions)

  (:types
    cell box
  )

  (:predicates
    (player-at ?c - cell)
    (box-at ?b - box ?c - cell)
    (clear ?c - cell)
    (goal ?c - cell)
    (deadlock ?c - cell)
    (filled ?c - cell)

    (up ?from - cell ?to - cell)
    (down ?from - cell ?to - cell)
    (left ?from - cell ?to - cell)
    (right ?from - cell ?to - cell)
  )

  (:action move-up
    :parameters (?from - cell ?to - cell)
    :precondition (and
      (player-at ?from)
      (up ?from ?to)
      (clear ?to)
    )
    :effect (and
      (not (player-at ?from))
      (player-at ?to)
      (clear ?from)
      (not (clear ?to))
    )
  )

  (:action move-down
    :parameters (?from - cell ?to - cell)
    :precondition (and
      (player-at ?from)
      (down ?from ?to)
      (clear ?to)
    )
    :effect (and
      (not (player-at ?from))
      (player-at ?to)
      (clear ?from)
      (not (clear ?to))
    )
  )

  (:action move-left
    :parameters (?from - cell ?to - cell)
    :precondition (and
      (player-at ?from)
      (left ?from ?to)
      (clear ?to)
    )
    :effect (and
      (not (player-at ?from))
      (player-at ?to)
      (clear ?from)
      (not (clear ?to))
    )
  )

  (:action move-right
    :parameters (?from - cell ?to - cell)
    :precondition (and
      (player-at ?from)
      (right ?from ?to)
      (clear ?to)
    )
    :effect (and
      (not (player-at ?from))
      (player-at ?to)
      (clear ?from)
      (not (clear ?to))
    )
  )

  (:action push-up
    :parameters (?b - box ?player - cell ?boxcell - cell ?dest - cell)
    :precondition (and
      (player-at ?player)
      (box-at ?b ?boxcell)
      (up ?player ?boxcell)
      (up ?boxcell ?dest)
      (clear ?dest)
      (not (deadlock ?dest))
      (not (goal ?boxcell))
      (not (goal ?dest))
    )
    :effect (and
      (not (player-at ?player))
      (player-at ?boxcell)
      (not (box-at ?b ?boxcell))
      (box-at ?b ?dest)
      (clear ?player)
      (not (clear ?boxcell))
      (not (clear ?dest))
    )
  )

  (:action push-up-to-goal
    :parameters (?b - box ?player - cell ?boxcell - cell ?dest - cell)
    :precondition (and
      (player-at ?player)
      (box-at ?b ?boxcell)
      (up ?player ?boxcell)
      (up ?boxcell ?dest)
      (clear ?dest)
      (not (goal ?boxcell))
      (goal ?dest)
    )
    :effect (and
      (not (player-at ?player))
      (player-at ?boxcell)
      (not (box-at ?b ?boxcell))
      (box-at ?b ?dest)
      (clear ?player)
      (not (clear ?boxcell))
      (not (clear ?dest))
      (filled ?dest)
    )
  )

  (:action push-up-from-goal
    :parameters (?b - box ?player - cell ?boxcell - cell ?dest - cell)
    :precondition (and
      (player-at ?player)
      (box-at ?b ?boxcell)
      (up ?player ?boxcell)
      (up ?boxcell ?dest)
      (clear ?dest)
      (not (deadlock ?dest))
      (goal ?boxcell)
      (not (goal ?dest))
      (filled ?boxcell)
    )
    :effect (and
      (not (player-at ?player))
      (player-at ?boxcell)
      (not (box-at ?b ?boxcell))
      (box-at ?b ?dest)
      (clear ?player)
      (not (clear ?boxcell))
      (not (clear ?dest))
      (not (filled ?boxcell))
    )
  )

  (:action push-up-goal-to-goal
    :parameters (?b - box ?player - cell ?boxcell - cell ?dest - cell)
    :precondition (and
      (player-at ?player)
      (box-at ?b ?boxcell)
      (up ?player ?boxcell)
      (up ?boxcell ?dest)
      (clear ?dest)
      (goal ?boxcell)
      (goal ?dest)
      (filled ?boxcell)
    )
    :effect (and
      (not (player-at ?player))
      (player-at ?boxcell)
      (not (box-at ?b ?boxcell))
      (box-at ?b ?dest)
      (clear ?player)
      (not (clear ?boxcell))
      (not (clear ?dest))
      (not (filled ?boxcell))
      (filled ?dest)
    )
  )

  (:action push-down
    :parameters (?b - box ?player - cell ?boxcell - cell ?dest - cell)
    :precondition (and
      (player-at ?player)
      (box-at ?b ?boxcell)
      (down ?player ?boxcell)
      (down ?boxcell ?dest)
      (clear ?dest)
      (not (deadlock ?dest))
      (not (goal ?boxcell))
      (not (goal ?dest))
    )
    :effect (and
      (not (player-at ?player))
      (player-at ?boxcell)
      (not (box-at ?b ?boxcell))
      (box-at ?b ?dest)
      (clear ?player)
      (not (clear ?boxcell))
      (not (clear ?dest))
    )
  )

  (:action push-down-to-goal
    :parameters (?b - box ?player - cell ?boxcell - cell ?dest - cell)
    :precondition (and
      (player-at ?player)
      (box-at ?b ?boxcell)
      (down ?player ?boxcell)
      (down ?boxcell ?dest)
      (clear ?dest)
      (not (goal ?boxcell))
      (goal ?dest)
    )
    :effect (and
      (not (player-at ?player))
      (player-at ?boxcell)
      (not (box-at ?b ?boxcell))
      (box-at ?b ?dest)
      (clear ?player)
      (not (clear ?boxcell))
      (not (clear ?dest))
      (filled ?dest)
    )
  )

  (:action push-down-from-goal
    :parameters (?b - box ?player - cell ?boxcell - cell ?dest - cell)
    :precondition (and
      (player-at ?player)
      (box-at ?b ?boxcell)
      (down ?player ?boxcell)
      (down ?boxcell ?dest)
      (clear ?dest)
      (not (deadlock ?dest))
      (goal ?boxcell)
      (not (goal ?dest))
      (filled ?boxcell)
    )
    :effect (and
      (not (player-at ?player))
      (player-at ?boxcell)
      (not (box-at ?b ?boxcell))
      (box-at ?b ?dest)
      (clear ?player)
      (not (clear ?boxcell))
      (not (clear ?dest))
      (not (filled ?boxcell))
    )
  )

  (:action push-down-goal-to-goal
    :parameters (?b - box ?player - cell ?boxcell - cell ?dest - cell)
    :precondition (and
      (player-at ?player)
      (box-at ?b ?boxcell)
      (down ?player ?boxcell)
      (down ?boxcell ?dest)
      (clear ?dest)
      (goal ?boxcell)
      (goal ?dest)
      (filled ?boxcell)
    )
    :effect (and
      (not (player-at ?player))
      (player-at ?boxcell)
      (not (box-at ?b ?boxcell))
      (box-at ?b ?dest)
      (clear ?player)
      (not (clear ?boxcell))
      (not (clear ?dest))
      (not (filled ?boxcell))
      (filled ?dest)
    )
  )

  (:action push-left
    :parameters (?b - box ?player - cell ?boxcell - cell ?dest - cell)
    :precondition (and
      (player-at ?player)
      (box-at ?b ?boxcell)
      (left ?player ?boxcell)
      (left ?boxcell ?dest)
      (clear ?dest)
      (not (deadlock ?dest))
      (not (goal ?boxcell))
      (not (goal ?dest))
    )
    :effect (and
      (not (player-at ?player))
      (player-at ?boxcell)
      (not (box-at ?b ?boxcell))
      (box-at ?b ?dest)
      (clear ?player)
      (not (clear ?boxcell))
      (not (clear ?dest))
    )
  )

  (:action push-left-to-goal
    :parameters (?b - box ?player - cell ?boxcell - cell ?dest - cell)
    :precondition (and
      (player-at ?player)
      (box-at ?b ?boxcell)
      (left ?player ?boxcell)
      (left ?boxcell ?dest)
      (clear ?dest)
      (not (goal ?boxcell))
      (goal ?dest)
    )
    :effect (and
      (not (player-at ?player))
      (player-at ?boxcell)
      (not (box-at ?b ?boxcell))
      (box-at ?b ?dest)
      (clear ?player)
      (not (clear ?boxcell))
      (not (clear ?dest))
      (filled ?dest)
    )
  )

  (:action push-left-from-goal
    :parameters (?b - box ?player - cell ?boxcell - cell ?dest - cell)
    :precondition (and
      (player-at ?player)
      (box-at ?b ?boxcell)
      (left ?player ?boxcell)
      (left ?boxcell ?dest)
      (clear ?dest)
      (not (deadlock ?dest))
      (goal ?boxcell)
      (not (goal ?dest))
      (filled ?boxcell)
    )
    :effect (and
      (not (player-at ?player))
      (player-at ?boxcell)
      (not (box-at ?b ?boxcell))
      (box-at ?b ?dest)
      (clear ?player)
      (not (clear ?boxcell))
      (not (clear ?dest))
      (not (filled ?boxcell))
    )
  )

  (:action push-left-goal-to-goal
    :parameters (?b - box ?player - cell ?boxcell - cell ?dest - cell)
    :precondition (and
      (player-at ?player)
      (box-at ?b ?boxcell)
      (left ?player ?boxcell)
      (left ?boxcell ?dest)
      (clear ?dest)
      (goal ?boxcell)
      (goal ?dest)
      (filled ?boxcell)
    )
    :effect (and
      (not (player-at ?player))
      (player-at ?boxcell)
      (not (box-at ?b ?boxcell))
      (box-at ?b ?dest)
      (clear ?player)
      (not (clear ?boxcell))
      (not (clear ?dest))
      (not (filled ?boxcell))
      (filled ?dest)
    )
  )

  (:action push-right
    :parameters (?b - box ?player - cell ?boxcell - cell ?dest - cell)
    :precondition (and
      (player-at ?player)
      (box-at ?b ?boxcell)
      (right ?player ?boxcell)
      (right ?boxcell ?dest)
      (clear ?dest)
      (not (deadlock ?dest))
      (not (goal ?boxcell))
      (not (goal ?dest))
    )
    :effect (and
      (not (player-at ?player))
      (player-at ?boxcell)
      (not (box-at ?b ?boxcell))
      (box-at ?b ?dest)
      (clear ?player)
      (not (clear ?boxcell))
      (not (clear ?dest))
    )
  )

  (:action push-right-to-goal
    :parameters (?b - box ?player - cell ?boxcell - cell ?dest - cell)
    :precondition (and
      (player-at ?player)
      (box-at ?b ?boxcell)
      (right ?player ?boxcell)
      (right ?boxcell ?dest)
      (clear ?dest)
      (not (goal ?boxcell))
      (goal ?dest)
    )
    :effect (and
      (not (player-at ?player))
      (player-at ?boxcell)
      (not (box-at ?b ?boxcell))
      (box-at ?b ?dest)
      (clear ?player)
      (not (clear ?boxcell))
      (not (clear ?dest))
      (filled ?dest)
    )
  )

  (:action push-right-from-goal
    :parameters (?b - box ?player - cell ?boxcell - cell ?dest - cell)
    :precondition (and
      (player-at ?player)
      (box-at ?b ?boxcell)
      (right ?player ?boxcell)
      (right ?boxcell ?dest)
      (clear ?dest)
      (not (deadlock ?dest))
      (goal ?boxcell)
      (not (goal ?dest))
      (filled ?boxcell)
    )
    :effect (and
      (not (player-at ?player))
      (player-at ?boxcell)
      (not (box-at ?b ?boxcell))
      (box-at ?b ?dest)
      (clear ?player)
      (not (clear ?boxcell))
      (not (clear ?dest))
      (not (filled ?boxcell))
    )
  )

  (:action push-right-goal-to-goal
    :parameters (?b - box ?player - cell ?boxcell - cell ?dest - cell)
    :precondition (and
      (player-at ?player)
      (box-at ?b ?boxcell)
      (right ?player ?boxcell)
      (right ?boxcell ?dest)
      (clear ?dest)
      (goal ?boxcell)
      (goal ?dest)
      (filled ?boxcell)
    )
    :effect (and
      (not (player-at ?player))
      (player-at ?boxcell)
      (not (box-at ?b ?boxcell))
      (box-at ?b ?dest)
      (clear ?player)
      (not (clear ?boxcell))
      (not (clear ?dest))
      (not (filled ?boxcell))
      (filled ?dest)
    )
  )
)
