(define (problem taquin-3x3-01)
  (:domain taquin)

  (:objects
    t1 t2 t3 t4 t5 t6 t7 t8 - tile
    c1 c2 c3 c4 c5 c6 c7 c8 c9 - cell
  )

  (:init
    (adjacent c1 c2)
    (adjacent c2 c1)
    (adjacent c2 c3)
    (adjacent c3 c2)
    (adjacent c1 c4)
    (adjacent c4 c1)
    (adjacent c2 c5)
    (adjacent c5 c2)
    (adjacent c3 c6)
    (adjacent c6 c3)
    (adjacent c4 c5)
    (adjacent c5 c4)
    (adjacent c5 c6)
    (adjacent c6 c5)
    (adjacent c4 c7)
    (adjacent c7 c4)
    (adjacent c5 c8)
    (adjacent c8 c5)
    (adjacent c6 c9)
    (adjacent c9 c6)
    (adjacent c7 c8)
    (adjacent c8 c7)
    (adjacent c8 c9)
    (adjacent c9 c8)

    (at t1 c1)
    (empty c2)
    (at t2 c3)
    (at t3 c4)
    (at t4 c5)
    (at t5 c6)
    (at t6 c7)
    (at t7 c8)
    (at t8 c9)
  )

  (:goal
    (and
      (empty c1)
      (at t1 c2)
      (at t2 c3)
      (at t3 c4)
      (at t4 c5)
      (at t5 c6)
      (at t6 c7)
      (at t7 c8)
      (at t8 c9)
    )
  )
)